name: pyharm

channels:
 - conda-forge

dependencies:
 - python=3.8
 - pip=24
 - psutil
 - numpy
 - scipy<=1.12.0
 - pandas
 - matplotlib
 - h5py
 - click
 - sphinx
 - pympler
 - ipykernel
 - ipympl
 - pytest
 - tqdm
