name: pyharm

channels:
 - conda-forge

dependencies:
 - python=3.9
 - Cython
 - mpi4py
 - pip
 - psutil
 - numpy<2
 - scipy
 - pandas
 - matplotlib
 - h5py
 - click
 - sphinx
 - pympler
 - ipykernel
 - ipympl
 - pytest
 - tqdm
